name: Pants-Test
on:
  pull_request:
    branches: 
     - '*'
     
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Pantsbuild-Tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9'] 
        architecture: ['x64'] 
    steps:
      - uses: actions/checkout@v2
      - name: PantsBuild Tests
      - uses: actions/setup-python@v2
        with: 
          python-version: ${{ matrix.python-version }}
          
      - name: Python version
        run: python --version
      - name: Pantsbuild Version
        run: ./pants --version
      - name: Test
        run: "./pants test src/python/{core,entrypoints}::"
      - name: Lint
        run: "./pants lint ::"
