# This is a basic workflow to help you get started with Actions

name: Pants-Test
on:
  pull_request:
    branches: 
     - '*'
     
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Pants-Tests:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9' 
          architecture: 'x64' 
          
      - name: Python version
        run: python --version
      - name: Pantsbuild Version
        run: ./pants --version
      - name: Test
        run: "./pants test src/python/{core,entrypoints}::"
      - name: Lint
        run: "./pants lint ::"

